### ISSUE TITLE
老铁这是I7还是i5版本？

### ISSUE THREAD

**Issue by pcyfox** [fl6145/xiaoxin700EFI#1]
I7还是i5版本？

**Comment by fulsun** [comment]
我是I5的

**Comment by pcyfox** [comment]
I7



---原始邮件---
发件人: "fulsun"<notifications@github.com&gt;
发送时间: 2020年12月7日(周一) 上午9:12
收件人: "fulsun/xiaoxin700EFI"<xiaoxin700EFI@noreply.github.com&gt;;
抄送: "东门喜"<1037050764@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [fulsun/xiaoxin700EFI] 老铁这是I7还是i5版本？ (#1)




 
我是I5的
